### ISSUE TITLE
Criação do CRUD de Adicionais (Criação, Leitura, Edição, Exclusão)

### ISSUE THREAD

**Issue by Rafael-Floriano** [EduardoDandolini/backend-lanches-senac#3]
### Cadastro de Adicionais:

```jsx
{baseUrl}/additional/save
```

Request Body:

```json
{
	"nome":"Batata Frita"
}
```

Response:

```json
201 CREATED - Empty Body
```

### Regras de negócio:

- Não deve ser possível cadastrar um novo adicional com um mesmo nome de um adicional já cadastrado na aplicação;
    - 409 Conflic - “Já existe um Adicional com esse nome no banco de dados”;

---

### Update de Adicional:

```jsx
{baseUrl}/additional/update
```

Request Body:

```json
{
	"id":1,
	"nome":"Batata"
}
```

Response:

```json
200 OK - Empty Body
```

### Regras de negócio:

- Não deve ser possível cadastrar um novo adicional com um mesmo nome de um adicional já cadastrado na aplicação;
    - 409 Conflic - “Já existe um Adicional com esse nome no banco de dados”;

---

### Delete de Adicional:

```jsx
{baseUrl}/additional/delete/{id}
```

Request Body:

```json
Empty
```

Response:

```json
200 OK - Empty Body
```

### Regras de negócio:

- Caso o adicional já não exista o sistema deve retornar uma exceção:
    - 404 Not Found - “Adicional não encontrado”;

---

### Listar Adicional:

```jsx
{baseUrl}/additional/list/all
```

Request Body:

```json
Empty
```

Response:

```json
{
	{
		"id":1,
		"nome":"Batata Frita"
	},
	{
		"id":2,
		"nome":"Maionese"
	}
}
```

**Comment by EduardoDandolini** [comment]
Para fazer, durante a semana iniciarei o desenvolvimento dessa demanda.

**Comment by EduardoDandolini** [comment]
Em andamento.

**Comment by Rafael-Floriano** [comment]
Desenvolvimento finalizado pelo @EduardoDandolini
